import requests
import pandas as pd
import time
from test import get_market_ids_from_excel

# Your list of symbols
my_list = [
    "AAPL", "AMZN", "BRENTOIL", "COIN", "XCU", "CRCL", "EURUSD",
    "XAU", "GOOGL", "HOOD", "HYUNDAI", "INTC", "USDJPY", "META",
    "MSFT", "MSTR", "NATGAS", "NVDA", "XPD", "XPT",
    "XAG", "SAMSUNG", "SKHYNIX", "SNDK", "TSLA"
]

# Path to the file generated by the previous script
file_name = "Lighter_Full_Market_List.xlsx"

# Get the IDs
market_map = get_market_ids_from_excel(file_name, my_list)

def fetch_candles(symbol, market_id):
    url = "https://mainnet.zklighter.elliot.ai/api/v1/candles"

    end_ts = int(time.time())
    # Corrected to 2 days: 2 * 24 * 60 * 60
    seconds_in_eight_days = 8 * 24 * 60 * 60
    start_ts = end_ts - seconds_in_eight_days

    params = {
        "market_id": market_id,
        "resolution": "1m",
        "start_timestamp": start_ts,
        "end_timestamp": end_ts,
        "count_back": 60
    }

    try:
        response = requests.get(url, params=params, headers={'accept': 'application/json'})
        response.raise_for_status()
        data = response.json()

        raw_candles = data.get('c', [])

        candles = []
        for item in raw_candles:
            # FIX: Added "timestamp" key and kept the curly braces for a valid dictionary
            candles.append({
                "timestamp": pd.to_datetime(item['t'], unit='ms') - pd.Timedelta(hours=8),
                "symbol": symbol,
                "open": item['o'],
                "high": item['h'],
                "low": item['l'],
                "close": item['c'],
                "volume": item['v']
            })
        return candles

    except Exception as e:
        print(f"Failed to fetch {symbol} (ID: {market_id}): {e}")
        return []


# --- Execution ---
all_data = []
for symbol, m_id in market_map.items():
    if m_id:  # Checks if m_id is not None or empty
        print(f"Fetching data for {symbol}...")
        data = fetch_candles(symbol, m_id)
        all_data.extend(data)
        # Optional: slight sleep to avoid hitting rate limits
        time.sleep(0.1)

if all_data:
    df = pd.DataFrame(all_data)
    # Ensure the columns are in a logical order
    df = df[["timestamp", "symbol", "open", "high", "low", "close", "volume"]]
    df.to_excel("Lighter_Market_Data.xlsx", index=False)
    print("Successfully saved to Lighter_Market_Data.xlsx")
else:
    print("No data was collected.")
